# This is a basic workflow to help you get started with Actions

name: Android CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
#  push:
#    branches: [ "master" ]
  pull_request:
    branches: [ "develop" ]

defaults:
  run:
    shell: bash

  # Allows you to run this workflow manually from the Actions tab

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build debug apk and test
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    #    container:
    #      image: cimg/android:2023.09.1-node

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Confirm Java Version
        run: java -version

      - name: Grant execute permission to gradle
        run: chmod +x ./gradlew

      #Check directory
      - name: Print working directory
        run: pwd

      - name: Build APK
        run: ./gradlew -p app assembleDebug

      - name: List APK Output
        run: ls -lh app/build/outputs/apk/debug

      - name: Clone target repository
        run: |
          git config --global user.name "github-action"
          git config --global user.email "ci@github-action"
          git clone https://x-access-token:${{ secrets.PAT }}@github.com/jamesLambertAsis/androidTechnical.git
          ls androidTechnical

      - name: Commit and push apk to androidTechnical
        run: |
          
          if [[ "${{github.event.pull_request.base.ref}}" == "develop" ]]; then
            git checkout -b develop origin/develop
            mkdir -androidTechinical/lib
            cp app/build/outputs/apk/debug
            cd androidTechnical
            git commit -m "CI: upload apk to anroid techinal" || echo "No changes to commit"
            git push origin develop
          fi
          
          
          

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
